### PR TITLE
Modify scheduling to allow the use of setTimeout

### PR DESCRIPTION
**Pull request by chpill**
Related to https://github.com/roman01la/citrus/issues/25

The big idea is to only schedule the update once, and to release the `scheduled?` lock at the end of the actual update.

I put the `(when-not @scheduled? ....)` part inside the `dispatch!` function, to avoid creating the `perform-batched-update` closure on each dispatch (it is now only created only once per batched-update).

As you can see, the `release-fn` is no longer used, so the change of the previous PR is no needed anymore... Maybe I should revert the `batched-update` back to a simple function.

### CODE REVIEW

**Comment by roman01la** [comment]
FYI, here's how React does scheduling https://github.com/facebook/react/blob/c7ce0091dcb2036e19df980247c9a4388ad75741/packages/shared/ReactDOMFrameScheduling.js Maybe you could find it useful.

**Comment by roman01la** [comment]
@chpill Do you think it's safe to merge this change? I don't really have time to test it. How does this change events execution in normal and background modes?

**Comment by chpill** [comment]
I haven't tested it a lot sadly. The project I was using it on at work has kind of stalled for other reasons, I don't know this modification will see production soon.

Having thought about this issue on and off for a while now, i'm beginning to wonder if the batching is worth it at all to be honest. In the context of react, I get why rum or reagent or om want to batch their updates (even if it's not something the react team encourages). Updating the DOM is very costly.

But for the state transitions of the app db, Is there that much efficiency to be gained? I guess I should check to see if the re-frame guys have some rationale for this.

**Comment by roman01la** [comment]
You might be right. My motivation was to have async dispatch so caller can do something else before dispatched logic runs, and batching was introduced to perform multiple state updates in a single `swap!` so that **Rum's subscriptions are triggered only once**. Given that a subscription can contain aggregation logic which runs on every update to app db, batching reduces the number of such runs.

**Comment by martinklepsch** [comment]
@chpill Hey! Are you eager to push this forward (rebase & push to verify in non-trivial code base) or should we close it for now?

**Comment by chpill** [comment]
@martinklepsch let's close this for now. Thanks for the reminder :+1:

**Pull request closed without merging**
